#,===============================================================================
#' Description:
#' Reproduce the Figure 5A
#===============================================================================
#' Article: Cascade 
#===============================================================================
#' Author: 
#' - Thaidy Moreno-Rodriguez
#===============================================================================
#' Date:  May 2023
#===============================================================================
#****************************************************************************
#' Uses ggstatsplot to plot Figure 5A
#****************************************************************************
################################################################################

#===============================================================================
#'  Loading libraries. 
#===============================================================================

library( rstatix )
library( ggpubr )
library( ggprism )
library( ggstatsplot ) 
library( gapminder )
library( car )
library( cowplot )

#===============================================================================
#' Statistical test per variable and plotting individual and as a whole panel 5A
#===============================================================================

# The data frames to run all the statistics analysis are generated by the 
# Prepare_cascade_enviroment_2023.R script
# The test used are reproduce manually and with ggstatsplot R package
set.seed(12345)

#===============================================================================
# First I check the distribution, normality of the data.

#Test each group for normality
ecDNA_stats_cascade%>%
    group_by(ecDNA_cat) %>%
    summarise(`W Stat` = shapiro.test(ploidy_PURPLE)$statistic,
              p.value = shapiro.test(ploidy_PURPLE)$p.value)
 
# # A tibble: 2 × 3
# ecDNA_cat `W Stat`  p.value
# <chr>        <dbl>    <dbl>
#   1 ecDNA(+)     0.826 0.00282 
#   2 ecDNA(-)     0.853 0.000327


# To check for variance:
leveneTest(data = ecDNA_stats_cascade, ploidy_PURPLE ~ ecDNA_cat) 
# Levene's Test for Homogeneity of Variance (center = median)
#       Df F value Pr(>F)
# group  1  6.6023 0.01315 *
#       51               
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# To check for normal distribution:
shapiro.test(ecDNA_stats_cascade$ploidy_PURPLE[ecDNA_stats_cascade$ecDNA_cat == "ecDNA(-)"]) 
# Shapiro-Wilk normality test
# 
# data:  ecDNA_stats_cascade_sub$ploidy_PURPLE[ecDNA_stats_cascade_sub$ecDNA_cat == "ecDNA_Neg"]
# W =0.853, p-value = 0.0003268
shapiro.test(ecDNA_stats_cascade$ploidy_PURPLE[ecDNA_stats_cascade$ecDNA_cat == "ecDNA(+)"]) 
# Shapiro-Wilk normality test
# 
# data:  ecDNA_stats_cascade$ploidy_PURPLE[ecDNA_stats_cascade$ecDNA_cat == "ecDNA_Pos"]
# W =0.82625, p-value = 0.002823
# Analized with type = np (non parametric)

#===============================================================================
# Perform manually the Mann-Whitney U test
m1<-wilcox.test(ploidy_PURPLE ~ ecDNA_cat, data=ecDNA_stats_cascade, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)
print(m1)
# Wilcoxon rank sum test with continuity correction
# 
# data:  ploidy_PURPLE by ecDNA_cat
# W = 182, p-value = 0.009123

#===============================================================================
# Plotting Ploidy 
p_1 <- ggbetweenstats(
  data             = ecDNA_stats_cascade,
  x                = ecDNA_cat,
  y                = ploidy_PURPLE,
  var.equal = T, 
  type = "np",
  centrality.plotting = F,
  title            = "CASCADE",
  xlab             = "",
  ylab = "Ploidy",
  point.args = list(position = ggplot2::position_jitterdodge(dodge.width = 0.6), alpha =
                      0.8, size = 2, stroke = 0, na.rm = TRUE), 
  ggsignif.args = list(textsize = 2, tip_length = 0.01),
  facet.proptest = T
) +
  ggplot2::scale_color_manual(values = c("#9CCB86", "#EB8D71" )) + 
  theme(text = element_text(size = 5),
        plot.subtitle = element_text(size = 3),
        plot.title = element_text(size = 5),
        legend.title = element_text(size = 5),
        legend.text = element_text(size = 5),
        panel.background = element_blank(),
        panel.grid.major.y = element_line(colour = "lightgrey", size = 0.1), 
        panel.grid.major.x = element_line(colour = "lightgrey", size = 0.1),
        panel.grid.minor.y = element_line(colour = "lightgrey", linetype = "dashed", size = 0.05),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75)) 
ggsave(plot = p_1,"Figure_5a_Ploidy.pdf", width=2.5,height=2.8)

#===============================================================================
# Statistis for SVtmbPerMb
#===============================================================================

# To check for variance:
leveneTest(data = ecDNA_stats_cascade, SVtmbPerMb ~ ecDNA_cat) 

# To test each group for normality
ecDNA_stats_cascade%>%
  group_by(ecDNA_cat) %>%
  summarise(`W Stat` = shapiro.test(SVtmbPerMb)$statistic,
            p.value = shapiro.test(SVtmbPerMb)$p.value)
# # A tibble: 2 × 3
# ecDNA_cat `W Stat`   p.value
# <chr>        <dbl>     <dbl>
# 1 ecDNA(+)     0.843 0.00524  
# 2 ecDNA(-)     0.825 0.0000815

# To check for distribution
shapiro.test(ecDNA_stats_cascade$SVtmbPerMb[ecDNA_stats_cascade$ecDNA_cat == "ecDNA(-)"]) 
shapiro.test(ecDNA_stats_cascade$SVtmbPerMb[ecDNA_stats_cascade$ecDNA_cat == "ecDNA(+)"]) 

#===============================================================================
# Perform the Mann-Whitney U test manually

m2<-wilcox.test(SVtmbPerMb ~ ecDNA_cat, data=ecDNA_stats_cascade, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)
print(m2)
# Wilcoxon rank sum test with continuity correction
# 
# data:  SVtmbPerMb by ecDNA_cat
# W = 120, p-value = 0.0001724
#===============================================================================

p_2 <- ggbetweenstats(
  data             = ecDNA_stats_cascade,
  x                = ecDNA_cat,
  y                = SVtmbPerMb,
  var.equal = T, 
  type = "np",
  centrality.plotting = F,
  title            = "CASCADE",
  xlab             = "",
  ylab = "SV TMBPerMb",
  point.args = list(position = ggplot2::position_jitterdodge(dodge.width = 0.6), alpha =
                      0.8, size = 2, stroke = 0, na.rm = TRUE), 
  ggsignif.args = list(textsize = 2, tip_length = 0.01),
  facet.proptest = T
) +
  ggplot2::scale_color_manual(values = c("#9CCB86", "#EB8D71" )) + 
  theme(text = element_text(size = 5),
        plot.subtitle = element_text(size = 3),
        plot.title = element_text(size = 5),
        legend.title = element_text(size = 5),
        legend.text = element_text(size = 5),
        panel.background = element_blank(),
        panel.grid.major.y = element_line(colour = "lightgrey", size = 0.1), 
        panel.grid.major.x = element_line(colour = "lightgrey", size = 0.1),
        panel.grid.minor.y = element_line(colour = "lightgrey", linetype = "dashed", size = 0.05),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75)) 
ggsave(plot = p_2, "Figure_5a_SVtmbPerMb.pdf", width=2.5,height=2.8)


#===============================================================================

# Pearson's chi-squared test = Hypothesis testing. Parametric/Non-parametric	Unpaired

#'==============================================================================
#' Chromothripsis 
#'==============================================================================

p_3 <- ggbarstats(
  data             = ecDNA_stats_cascade,
  x                = Chromothripsis,
  y                = 'ecDNA_cat',
  title            = "Chromothripsis",
  label.fill.alpha = 0.5,
  xlab             = "",
  ylab             = NULL,
  label.fill.alpha = 0.5,
  label = "counts",
  label.text.size = 20,
  bf.message = FALSE,
  fixed.margin = rows,
  legend.title    = "Alterations", 
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  facet.proptest = TRUE
) + 
  scale_fill_manual(values = alpha(c("#E6A024", "#5BB4E5"), 0.75) ) +
  theme(text = element_text(size = 5),
        plot.subtitle = element_text(size = 3),
        plot.title = element_text(size = 5),
        legend.title = element_text(size = 5),
        legend.text = element_text(size = 5),
        panel.background = element_blank(),
        panel.grid.major.y = element_line(colour = "lightgrey", size = 0.1), 
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(colour = "lightgrey", linetype = "dashed", size = 0.05),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        legend.position = "none") 

extract_stats(p_3)
ggsave(plot = p_3, "Figure_5a_Chromothripsis.pdf", width=1.5,height=2.8)

 
#'==============================================================================
#' TP53 
#'==============================================================================
 
p_4 <- ggbarstats(
  data             = ecDNA_stats_cascade,
  x                = TP53,
  y                = 'ecDNA_cat',
  title            = "TP53",
  label.fill.alpha = 0.5,
  xlab             = "",
  ylab             = NULL,
  label.fill.alpha = 0.5,
  label = "counts",
  label.text.size = 20,
  bf.message = FALSE,
  fixed.margin = rows,
  legend.title = NULL, 
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  facet.proptest = TRUE
) + 
  scale_fill_manual(values = alpha(c("#E6A024", "#5BB4E5"), 0.75) ) +
  theme(text = element_text(size = 5),
        plot.subtitle = element_text(size = 3),
        plot.title = element_text(size = 5),
        legend.title = element_text(size = 5),
        legend.text = element_text(size = 5),
        panel.background = element_blank(),
        panel.grid.major.y = element_line(colour = "lightgrey", size = 0.1), 
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(colour = "lightgrey", linetype = "dashed", size = 0.05),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        legend.position = "none") 

extract_stats(p_4)
ggsave(plot = p_4, "Figure_5a_TP53.pdf", width=1.5,height=2.8)

#'==============================================================================
#' PTEN 
#'==============================================================================

p_5 <- ggbarstats(
  data             = ecDNA_stats_cascade,
  x                = PTEN,
  y                = 'ecDNA_cat',
  title            = "PTEN",
  label.fill.alpha = 0.5,
  xlab             = "",
  ylab             = NULL,
  label.fill.alpha = 0.5,
  label = "counts",
  label.text.size = 20,
  bf.message = FALSE,
  fixed.margin = rows,
  legend.title = NULL, 
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  facet.proptest = TRUE
) + 
  scale_fill_manual(values = alpha(c("#E6A024", "#5BB4E5"), 0.75) ) +
  theme(text = element_text(size = 5),
        plot.subtitle = element_text(size = 3),
        plot.title = element_text(size = 5),
        legend.title = element_text(size = 5),
        legend.text = element_text(size = 5),
        panel.background = element_blank(),
        panel.grid.major.y = element_line(colour = "lightgrey", size = 0.1), 
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(colour = "lightgrey", linetype = "dashed", size = 0.05),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        legend.position = "none") 

extract_stats(p_5)
ggsave(plot = p_5, "Figure_5a_PTEN.pdf", width=1.5,height=2.8)

#'==============================================================================
#' List of plots  
#'==============================================================================

# create a list with the plots
p_list_cascade<- list(p_1, p_2, p_3, 
                      p_4, p_5) 

# extract a legend that is laid out horizontally
legend_c_d <- get_legend(
  p_3 + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom") )

# combining plots
prow <- cowplot::plot_grid(
  plotlist = p_list_cascade,   nrow = 1, ncol = 5,
  align = "h",  rel_widths = c(2, 2, 1.3, 1.3,1.3), axis = "b")
# add the legend underneath the row we made earlier resized at 10%

prow2 <- cowplot::plot_grid(prow, legend_c_d, ncol = 1, rel_heights = c(1, .1))
ggsave(plot =prow2, "Figures_5A.pdf", width=9,height=3)
